# Generated by Django 3.0.7 on 2020-07-24 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=5000)),
                ('active', models.BooleanField(default=True)),
                ('consultation_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_key', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctors')),
            ],
            options={
                'verbose_name': 'consultations',
                'verbose_name_plural': 'consultations',
                'db_table': 'consultations',
                'ordering': ('-timestamp',),
            },
        ),
    ]
