# Generated by Django 3.0.7 on 2020-08-31 04:38

import accounts.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, help_text='Copy This Data From Firebase UUID AccountKit', max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=accounts.models.upload_image_path)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('street', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(choices=[('Lagos', 'Lagos'), ('Imo', 'Imo'), ('Anambra', 'Anambra')], default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'db_table': 'profile',
                'unique_together': {('phone', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('relationship', models.CharField(choices=[('Brother', 'Brother'), ('Sister', 'Sister'), ('Mom', 'Mom'), ('Dad', 'Dad'), ('Step Mom', 'Step Mom'), ('Step Dad', 'Step Dad'), ('Grand Mom', 'Grand Mom'), ('Grand Dad', 'Grand Dad'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Guardian', 'Guardian'), ('Friend', 'Friend')], default='', help_text='Relationship with Next Of Kin', max_length=300)),
                ('bio', models.TextField(blank=True, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('street', models.CharField(default='', max_length=300)),
                ('city', models.CharField(default='', max_length=200)),
                ('state', models.CharField(choices=[('Lagos', 'Lagos'), ('Imo', 'Imo'), ('Anambra', 'Anambra')], default='', max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Informant',
                'verbose_name_plural': 'Informant',
                'db_table': 'NextOfKin',
                'unique_together': {('phone',)},
            },
        ),
    ]
