# Generated by Django 3.0.7 on 2021-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='is_on_promo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
