# Generated by Django 3.0.7 on 2020-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
