# Generated by Django 3.0.7 on 2020-08-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_speciality_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='description',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
